name: release

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: FreeBSD-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-freebsd
            bin: precious
            name: precious-FreeBSD-x86_64.tar.gz
            command: build

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: precious.exe
            name: precious-Windows-x86_64.zip
            command: both

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: precious
            name: precious-Darwin-x86_64.tar.gz
            command: both

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --verbose
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

    # - name: Upload release
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     body_path: CHANGELOG.md
    #     files: |
    #       dist/ts_deplint-linux.tar.gz
    #       dist/ts_deplint-macos.tar.gz
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Publish npm package
    #   env:
    #     NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
    #   run: |
    #     echo "//registry.npmjs.org/:_authToken=$NPM_ACCESS_TOKEN" > ".npmrc"
    #     npm publish

    # - name: Publish cargo package
    #   env:
    #     CARGO_ACCESS_TOKEN: ${{ secrets.CARGO_ACCESS_TOKEN }}
    #   run: |
    #     cargo login "$CARGO_ACCESS_TOKEN"
    #     cargo publish
